[platformio]
default_envs = lolin_esp32s2_mini

[env:lolin_esp32s2_mini]
;platform = espressif32@6.5.0
platform = espressif32@6.3.2
board = lolin_s2_mini
framework = arduino

upload_speed = 921600
;upload_port = COM15
upload_flags =
    --after
    no_reset
monitor_speed = 115200
;monitor_port = COM15
monitor_dtr = 1
monitor_rts = 1
monitor_filters = skip_opening

build_flags =
    -DBUILD_UNIX_TIME=$UNIX_TIME  ;supposed to procide compile date and time to the code, but it does not work. It always provides the same value, which is the time of the first compilation. I have no idea why.
    -DSERIAL_DEBUG_ENABLE=1        ; production default: compile out all DBG_* serial output
    -I include
    -D VERSION_NAME=\"DS3231_TEST\"  ;change here to change the version name, which is displayed on the OLED screen. It is also used in the filename of the log file. The version name is also stored in the EEPROM, so that it can be read back after a reset or power cycle. The version name is also used to determine if the EEPROM needs to be initialized or not. If the version name in the EEPROM does not match the version name in the code, then the EEPROM is initialized with default values.
    

;a comment

board_build.usb_cdc_on_boot = 0
board_build.usb_mode = SERIAL_ONLY
upload_protocol = esptool

lib_ldf_mode = deep+

lib_deps =
    olikraus/U8g2 @ ^2.36.17
    wire
    SPI
    adafruit/RTClib @ ^2.1.4

build_src_filter = 
    +<main.cpp>
    ;+<main_ds3231_test.cpp>
    ;+<main_ds3231_test_2.cpp>
    ;+<main_ds3231_alarm_test.cpp>
    ;+<main_ds3231_interrupt_test.cpp>
    ;+<main_pb_top_timer_test.cpp>
    ;+<main_NTP_test.cpp>
    ;+<main-sleepTest.cpp>
    ;+<archive/main-ADC_calibrate.cpp>
    ;+<main_alog_calibration_OLED.cpp>
    ;+<main-test.cpp>
    ;+<archive/main-buttonTest.cpp>
    ;+<ext1_wakeup_test.cpp>
    ;+<light_sleep_wakeup_test.cpp>
    ;+<light_and_deep_sleep_wakeup_test.cpp>
    ;+<GROK-TEST.CPP>  
    ;+<archive\main-buttonTest.cpp>  










